### ISSUE TITLE
Certificate renewal

### ISSUE THREAD

**Issue by Muppetteer** [SlothCroissant/caddy-cloudflaredns#3]
Does this image handle certificate renewal automatically? I set it up a few months ago and I'm getting emails from the Let's Encrypt Certificate Bot warning me that my certificates will soon expire (in 11 days). If not, do you know of how to manually force a renewal? Thanks

**Comment by SlothCroissant** [comment]
It should renew them just fine - all the image does is use Caddy's built-in build mechanism, nothing special:

https://github.com/SlothCroissant/caddy-cloudflaredns/blob/master/Dockerfile

The certificate renewal piece is within your configuration, so you'd have to check there to see how you have it configured (or if you use the defaults). Check the caddy docs for ref: https://caddyserver.com/docs/automatic-https

I'd also review logs as well - I once had renewal failures due to DNS issues in my network, as Caddy was unable to check the DNS01 challenge (even though the TXT record was fine). Only way I found that was by watching logs. Caddy usually checks certs on bootup, so simply rebooting the container often will get you some usable logs to review what it shows might be happening.

**Comment by Muppetteer** [comment]
Thanks, you're right. It looks like it has in fact renewed most of my subdomains, except for 2 which I found certs for in a different subdirectory. Everything in "acme-v02.api.letsencrypt.org-directory" had been renewed in March except for 2 subdomains that were dated January. But I also found certs dated March for those 2 in another subdirectory with "acme-zerossl" in it. I don't know why or how they were renewed on a different endpoint but I just deleted that entire zerossl subdirectory and restarted caddy and it renewed them in the original letsencrypt directory.
